theme: jekyll-theme-minimal
title: Ben LaVergne
description: Technical writer and documentation engineer with 14 years of experience documenting telecom and security products. I combine hands-on product testing, information architecture, and custom tooling to make complex software easier to use.<br/>To email me, use my GitHub username and the domain proton.me.
